Repository GIScience/ohsome-quality-api, pull requests merged in 2021-08, with the labels that each got.

#125 Jenkinsfile: add missing space for sonar-scanner
  Jenkinsfile
Labels: CI

#126 ignore “Bug” raised by SonarCloud
  workers/tests/unittests/test_api.py
  workers/tests/unittests/test_ohsome_client.py
Labels: code quality, tests

#127 drop unused UI code, and dependency to jQuery completely
  website/website/assets/js/map-en.js
  website/website/index.html
Labels: dependencies, comments welcome, website

#143 Update usage section in README
  README.md
Labels: documentation

#141 Adding documentation on “How to add a layer definition”
  CHANGELOG.md
  README.md
  docs/layer.md
  workers/ohsome_quality_analyst/ohsome/layer_definitions.yaml
Labels: documentation

#160 Update database recreation docs
  docs/development_setup.md
Labels: documentation

#102 Add pydantic request models and documentation to API
  CHANGELOG.md
  workers/ohsome_quality_analyst/__init__.py
  workers/ohsome_quality_analyst/api.py
  workers/ohsome_quality_analyst/api/api.py
  workers/ohsome_quality_analyst/api/request_models.py
  workers/ohsome_quality_analyst/cli/cli.py
  workers/ohsome_quality_analyst/cli/options.py
  workers/ohsome_quality_analyst/utils/definitions.py
  workers/ohsome_quality_analyst/utils/helper.py
  workers/poetry.lock
  workers/pyproject.toml
  workers/scripts/start_api.py
  workers/setup.cfg
  workers/tests/integrationtests/api_response_schema.py
  workers/tests/integrationtests/test_api.py
  workers/tests/integrationtests/test_api_indicator.py
  workers/tests/integrationtests/test_api_indicator_geojson_io.py
  workers/tests/integrationtests/test_api_report.py
  workers/tests/integrationtests/test_api_report_geojson_io.py
  workers/tests/integrationtests/test_cli.py
  workers/tests/integrationtests/test_cli_geojson_io.py
  workers/tests/unittests/test_api.py
  workers/tests/unittests/test_api_request_models.py
  workers/tests/unittests/test_cli.py
  workers/tests/unittests/test_definitions.py
  workers/tests/unittests/test_helper.py
Labels: enhancement
