Repository GIScience/ohsome-quality-api, pull requests merged in 2021-05, with the labels that each got.

#15 change branch references from master to main
  CONTRIBUTING.md
  Jenkinsfile
  README.md
Labels: CI, documentation

#17 add Rocket.Chat notifications
  .github/workflows/rocketchat-notifications-feedback-requests.yml
Labels: waiting for review

#19 Fix wrong layer name for Map Action Report
  CHANGELOG.md
  workers/ohsome_quality_analyst/__init__.py
  workers/ohsome_quality_analyst/reports/map_action_poc/report.py
  workers/pyproject.toml
Labels: bug

#18 Add Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: code quality, waiting for review

#16 add "current main" to changelog
  CHANGELOG.md
Labels: documentation

#25 Update documentation
  CONTRIBUTING.md
  README.md
  docs/development_setup.md
  docs/indicator_creation.md
Labels: documentation, waiting for review

#28 Check for invalid indicator layer combination during initialization of indicator objects
  CHANGELOG.md
  workers/ohsome_quality_analyst/base/indicator.py
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_tags_ratio.json
  workers/tests/integrationtests/test_indicator_tags_ratio.py
Labels: bug

#41 sonar: fix project name
  sonar-project.properties
Labels: CI
