Repository GIScience/ohsome-quality-api, pull requests merged in 2021-06, with the labels that each got.

#40 Add flake8 plugin pep8-naming as development dependency
  CHANGELOG.md
  workers/ohsome_quality_analyst/api.py
  workers/ohsome_quality_analyst/indicators/ghs_pop_comparison_buildings/indicator.py
  workers/ohsome_quality_analyst/indicators/ghs_pop_comparison_roads/indicator.py
  workers/ohsome_quality_analyst/indicators/last_edit/indicator.py
  workers/ohsome_quality_analyst/indicators/mapping_saturation/sigmoid_curve.py
  workers/ohsome_quality_analyst/indicators/poi_density/indicator.py
  workers/ohsome_quality_analyst/indicators/tags_ratio/indicator.py
  workers/poetry.lock
  workers/pyproject.toml
  workers/setup.cfg
  workers/tests/integrationtests/test_cli.py
  workers/tests/integrationtests/test_indicator_mapping_saturation.py
  workers/tests/integrationtests/test_oqt.py
  workers/tests/unittests/test_api.py
  workers/tests/unittests/test_cli.py
Labels: code quality

#42 add test coverage config to sonar properties
  sonar-project.properties
Labels: CI

#29 Raise exceptions in ohsome client instead of returning None in case of failed ohsome API query
  CHANGELOG.md
  workers/ohsome_quality_analyst/ohsome/client.py
  workers/ohsome_quality_analyst/utils/exceptions.py
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_last_edit.json
  workers/tests/unittests/fixtures/ohsome-response-400-time.json
  workers/tests/unittests/test_ohsome_client.py
Labels: bug, code quality

#37 Add option to select different datasets and fid fields as input to OQT
  CHANGELOG.md
  workers/ohsome_quality_analyst/api.py
  workers/ohsome_quality_analyst/base/report.py
  workers/ohsome_quality_analyst/cli.py
  workers/ohsome_quality_analyst/cli_opts.py
  workers/ohsome_quality_analyst/geodatabase/client.py
  workers/ohsome_quality_analyst/geodatabase/create_results_table.sql
  workers/ohsome_quality_analyst/geodatabase/load_results.sql
  workers/ohsome_quality_analyst/geodatabase/save_results.sql
  workers/ohsome_quality_analyst/oqt.py
  workers/ohsome_quality_analyst/reports/jrc_requirements/report.py
  workers/ohsome_quality_analyst/reports/map_action_poc/report.py
  workers/ohsome_quality_analyst/reports/remote_mapping_level_one/report.py
  workers/ohsome_quality_analyst/reports/simple_report/report.py
  workers/ohsome_quality_analyst/reports/sketchmap_fitness/report.py
  workers/ohsome_quality_analyst/utils/definitions.py
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_report.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_cli.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_geodatabase.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_ghs_pop_comparison_buildings.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_last_edit.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_mapping_saturation.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_tags_ratio.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_oqt.json
  workers/tests/integrationtests/test_api_indicator.py
  workers/tests/integrationtests/test_api_report.py
  workers/tests/integrationtests/test_cli.py
  workers/tests/integrationtests/test_geodatabase.py
  workers/tests/integrationtests/test_indicator_ghs_pop_comparison_buildings.py
  workers/tests/integrationtests/test_indicator_ghs_pop_comparison_roads.py
  workers/tests/integrationtests/test_indicator_last_edit.py
  workers/tests/integrationtests/test_indicator_mapping_saturation.py
  workers/tests/integrationtests/test_indicator_tags_ratio.py
  workers/tests/integrationtests/test_oqt.py
  workers/tests/unittests/test_cli.py
  workers/tests/unittests/test_cli_opts.py
Labels: enhancement

#47 Formating Python datetime object to ISO when outputting a GeoJSON
  workers/ohsome_quality_analyst/cli.py
  workers/ohsome_quality_analyst/utils/helper.py
  workers/tests/unittests/test_datetime_to_isostring.py
Labels: bug

#57 Writing GeoJSON from the CLI for indicator/report calculation when using datasets
  CHANGELOG.md
  workers/ohsome_quality_analyst/cli.py
  workers/ohsome_quality_analyst/utils/helper.py
  workers/tests/integrationtests/fixtures/heidelberg-altstadt-feature.geojson
  workers/tests/integrationtests/fixtures/heidelberg-altstadt-geometry.geojson
  workers/tests/integrationtests/fixtures/heidelberg-bahnstadt-bergheim-featurecollection.geojson
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_cli_file_io.json
  workers/tests/integrationtests/test_cli_file_io.py
Labels: enhancement

#27 Redefine OQT regions
  CHANGELOG.md
  database/init_db.development/schema.test.sql
  database/init_db.production/GADM.sh
  database/init_db.production/NUTS_2021.sh
  database/init_db.production/init_db.sh
  database/init_db.production/regions.sh
  database/init_db.production/regions.sql
  database/scripts/development-database/create_dev_schema.sql
  database/scripts/development-database/dump_dev_schema.sh
  database/scripts/development-database/remove_dev_schema.sql
  database/scripts/import/GHS-SMOD.sh
  database/scripts/import/SHDI.sh
  database/scripts/import/insert_srid_54009.sql
  database/scripts/oqt-regions/degree-of-urbanisations.sql
  database/scripts/oqt-regions/gadm_unit_to_regions.sql
  database/scripts/oqt-regions/shdi.sql
  workers/tests/integrationtests/fixtures/CH_Basel_Stadt_good.geojson
  workers/tests/integrationtests/fixtures/Phil_Manila_medium.geojson
  workers/tests/integrationtests/fixtures/UK_London_Westminster_good.geojson
  workers/tests/integrationtests/fixtures/US_NewYork_Manhatten_Harlem.geojson
  workers/tests/integrationtests/fixtures/antanarivo.geojson
  workers/tests/integrationtests/fixtures/niger-kanan-bakache.geojson
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_report.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_cli.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_geodatabase.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_ghs_pop_comparison_buildings.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_last_edit.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_mapping_saturation.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_poi_density.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_tags_ratio.json
  workers/tests/integrationtests/fixtures/vcr_cassettes/test_oqt.json
  workers/tests/integrationtests/test_api_indicator.py
  workers/tests/integrationtests/test_api_report.py
  workers/tests/integrationtests/test_cli.py
  workers/tests/integrationtests/test_geodatabase.py
  workers/tests/integrationtests/test_indicator_ghs_pop_comparison_buildings.py
  workers/tests/integrationtests/test_indicator_ghs_pop_comparison_roads.py
  workers/tests/integrationtests/test_indicator_last_edit.py
  workers/tests/integrationtests/test_indicator_mapping_saturation.py
  workers/tests/integrationtests/test_indicator_tags_ratio.py
  workers/tests/integrationtests/test_oqt.py
Labels: enhancement
