Repository GIScience/ohsome-quality-api, pull requests merged in 2021-07, with the labels that each got.

#72 Added workaround for failing DB-build using Windows to troubleshooting doc
  docs/troubleshooting.md
Labels: documentation, waiting for review

#91 Rearrange Changelog
  CHANGELOG.md
Labels: documentation, waiting for review

#92 rearrange changes to other topics
  CHANGELOG.md
Labels: documentation

#110 Minor improvements to the metadata and docstrings of indicators
  CHANGELOG.md
  workers/ohsome_quality_analyst/indicators/last_edit/indicator.py
  workers/ohsome_quality_analyst/indicators/last_edit/metadata.yaml
  workers/ohsome_quality_analyst/indicators/mapping_saturation/metadata.yaml
  workers/ohsome_quality_analyst/indicators/poi_density/metadata.yaml
Labels: waiting for review

#112 Fix error raising while serializing JSON due NaN
  CHANGELOG.md
  workers/ohsome_quality_analyst/cli.py
  workers/ohsome_quality_analyst/utils/helper.py
Labels: bug, priority:high
