Repository GIScience/ohsome-quality-api, pull requests merged in 2022-09, with the labels that each got.

#416 rename layer ideal_vgi_infrastructure to basic_infrastructure
  CHANGELOG.md
  workers/ohsome_quality_analyst/definitions.py
  workers/ohsome_quality_analyst/ohsome/layer_definitions.yaml
  workers/ohsome_quality_analyst/reports/multilevel_mapping_saturation/report.py
Labels: brainstorming

#427 feat: add mapaction priority countries to database
  CHANGELOG.md
  database/init_db.development/schema.test.sql
  database/scripts/development-database/create_dev_schema.sql
  database/scripts/development-database/remove_dev_schema.sql
Labels: waiting for review, database

#426 fix: rename layer ideal_vgi_infrastructure
  CHANGELOG.md
  workers/ohsome_quality_analyst/definitions.py
  workers/ohsome_quality_analyst/reports/multilevel_currentness/report.py
Labels: bug, waiting for review

#428 fix(db): import of mapaction priority countries
  CHANGELOG.md
  database/init_db.development/post-init-db.sql
  database/scripts/development-database/remove_dev_schema.sql
Labels: bug

#436 Temporary fix for sonar-scanner node version
  workers/Dockerfile.continuous-integration
Labels: CI, waiting for review

#438 fix: change layer names to avoid duplication
  CHANGELOG.md
  workers/ohsome_quality_analyst/ohsome/layer_definitions.yaml
Labels: bug
