Repository GIScience/ohsome-quality-api, pull requests merged in 2024-09, with the labels that each got.

#817 Run build and tests in Jenkins outside docker
  Dockerfile.continuous-integration
  Jenkinsfile
Labels: CI

#822 fix typo in attributes.yaml
  ohsome_quality_api/attributes/attributes.yaml
Labels: bug

#824 feat(api): use `geojson-pydantic` as request model
  CHANGELOG.md
  ohsome_quality_api/api/request_models.py
Labels: waiting for review

#673 refactor(indicators): separate templates from metadata and merge all metadata files
  CHANGELOG.md
  ohsome_quality_api/api/api.py
  ohsome_quality_api/definitions.py
  ohsome_quality_api/indicators/attribute_completeness/indicator.py
  ohsome_quality_api/indicators/attribute_completeness/metadata.yaml
  ohsome_quality_api/indicators/attribute_completeness/templates.yaml
  ohsome_quality_api/indicators/base.py
  ohsome_quality_api/indicators/building_comparison/indicator.py
  ohsome_quality_api/indicators/building_comparison/metadata.yaml
  ohsome_quality_api/indicators/building_comparison/templates.yaml
  ohsome_quality_api/indicators/currentness/indicator.py
  ohsome_quality_api/indicators/currentness/metadata.yaml
  ohsome_quality_api/indicators/currentness/templates.yaml
  ohsome_quality_api/indicators/definitions.py
  ohsome_quality_api/indicators/density/indicator.py
  ohsome_quality_api/indicators/density/metadata.yaml
  ohsome_quality_api/indicators/density/templates.yaml
  ohsome_quality_api/indicators/indicators.yaml
  ohsome_quality_api/indicators/mapping_saturation/indicator.py
  ohsome_quality_api/indicators/mapping_saturation/metadata.yaml
  ohsome_quality_api/indicators/mapping_saturation/templates.yaml
  ohsome_quality_api/indicators/minimal/indicator.py
  ohsome_quality_api/indicators/minimal/metadata.yaml
  ohsome_quality_api/indicators/minimal/templates.yaml
  ohsome_quality_api/indicators/models.py
  ohsome_quality_api/indicators/road_comparison/indicator.py
  ohsome_quality_api/indicators/road_comparison/metadata.yaml
  ohsome_quality_api/indicators/road_comparison/templates.yaml
  tests/conftest.py
  tests/integrationtests/test_base_indicator.py
  tests/unittests/test_definitions.py
  tests/unittests/test_helper.py
  tests/unittests/test_indicators_definitions.py
Labels: waiting for review
